"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.1.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8b5tcv*bk5-6eb9g2a&4x-$oap8ojt35f4kd@b)y&9feyx0d5^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'rest_framework',
    'django_filters',
    'newtask',
    'base',
    'conversion'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'newtask.middleware.WorkingHoursMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lms.urls'

import os

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # 👈 must match the path above
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_HOST_USER = 'sakshiverma9024@gmail.com'
EMAIL_HOST_PASSWORD = 'qfne wkgu axdt zyez'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


REST_FRAMEWORK = {
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'PAGE_SIZE' : 5,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '2/m',  # 2 requests per minute
        'user': '4/m'
    }
}


CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'https://yourfrontend.com']
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# JAZZMIN_SETTINGS = {
#     "site_title": "LMS Admin",
#     "site_header": "Learning Management System",
#     "site_brand": "LMS Portal",
#     "welcome_sign": "Welcome to LMS Admin Dashboard",
#     "copyright": "LMS © 2025",
#     "show_ui_builder": True,


#     # Dark mode theme
#     "theme": "darkly",  # you can try "cyborg", "superhero", "flatly" also

#     # Top menu links
#     "topmenu_links": [
#         {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
#         {"app": "myapp"},     # links to whole app
#         {"app": "newtask"},
#         {"model": "myapp.Bookss"},
#         {"model": "newtask.Employee"},
#     ],

#     # Sidebar settings
#     "show_sidebar": True,
#     "navigation_expanded": False,  # collapsible sidebar
#     "order_with_respect_to": ["myapp", "newtask"],

#     # Icons for apps & models
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.User": "fas fa-user",
#         "auth.Group": "fas fa-users",

#         "myapp": "fas fa-book",
#         "myapp.Authors": "fas fa-user-edit",
#         "myapp.Bookss": "fas fa-book-open",
#         "myapp.UserBooks": "fas fa-book-reader",
#         "myapp.UserProfiles": "fas fa-id-badge",

#         "newtask": "fas fa-tasks",
#         "newtask.Attendances": "fas fa-calendar-check",
#         "newtask.Departments": "fas fa-building",
#         "newtask.Employees": "fas fa-user-tie",
#         "newtask.Roles": "fas fa-user-shield",
#     },

#     # UI tweaks
#     "changeform_format": "collapsible",  # collapsible sections in forms
#     "changeform_format_overrides": {"auth.user": "vertical_tabs"},
# }

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "myapp" / "static"]