# Generated by Django 5.2.4 on 2025-08-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newtask.common')),
                ('title', models.CharField(max_length=200)),
                ('level_type', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')])),
                ('description', models.TextField(max_length=500)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TextField()),
            ],
            bases=('newtask.common',),
        ),
    ]
