# Generated by Django 5.2.4 on 2025-08-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0003_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='common_ptr',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Common',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
