# Generated by Django 5.2.4 on 2025-08-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('level_type', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')])),
                ('description', models.TextField(max_length=500)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
