# Generated by Django 5.2.4 on 2025-08-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(blank=True, choices=[('office', 'Office'), ('wfh', 'Work_From_Home')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half_Day')], max_length=50, null=True)),
                ('late_check_in', models.BooleanField(default=False)),
                ('early_check_out', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newtask.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
