# Generated by Django 5.2.4 on 2025-08-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0008_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
