# Generated by Django 5.2.4 on 2025-08-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtask', '0009_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='exit_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='level_type',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], max_length=200),
        ),
    ]
