# Generated by Django 5.2.4 on 2025-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=50),
        ),
    ]
