# Generated by Django 5.2.4 on 2025-07-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('renting_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='myapp.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.userprofile')),
            ],
        ),
    ]
