# Generated by Django 5.2.4 on 2025-08-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='type',
            field=models.CharField(choices=[('S', 'Sale'), ('R', 'Rent')], max_length=200),
        ),
    ]
